name: LeagueSystem
main: io.bbrl.leaguesystem.Main
version: 0.8.18
api-version: 1.20
authors: [BBRL]
commands:
  league:
    description: League management root command
    usage: /league <subcommand>
    permission: bbrl.league.use
permissions:
  bbrl.league.use:
    description: Allows use of the /league base command
    default: op
